src/WebUI/Controllers/CustomerDataController.cs
using System.Collections.Generic;
using System.Reflection;
using AutoMapper;
using MediatR;
using Medical_Optics.Application.Common.Enums;
using Medical_Optics.Application.Common.Interfaces;
using Medical_Optics.Application.Common.Resources;
using Medical_Optics.Application.Def.City.Queries.GetAll;
using Medical_Optics.Application.Def.Nationality.Queries.GetAll;
using Medical_Optics.Application.HR.SocialStatus.Queries.GetAll;
using Medical_Optics.Application.Optic.Complaint.Commands.Create;
using Medical_Optics.Application.Optic.Complaint.Commands.Update;
using Medical_Optics.Application.Optic.Complaint.Queries.GetAll;
using Medical_Optics.Application.Optic.Complaint.Queries.GetById;
using Medical_Optics.Application.Optic.CustomerData.Commands.Create;
using Medical_Optics.Application.Optic.CustomerData.Commands.ViewModels;
using Medical_Optics.Application.Optic.CustomerData.Queries.GetAll;
using Medical_Optics.Application.Optic.CustomerData.Queries.GetById;
using Medical_Optics.Application.Optic.DefReligion.Queries.GetAll;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory.Database;

namespace Medical_Optics.WebUI.Controllers;
public class CustomerDataController : BaseController
{
    private readonly IMapper _mapper;
    private readonly IFileHandler _fileHandler;

    public CustomerDataController(IMapper mapper, IFileHandler fileHandler)
    {
        _mapper = mapper;
        _fileHandler = fileHandler;
    }

    public async Task<IActionResult> IndexAsync()
    {
        var PatientsFiles = await Mediator.Send(new GetAllPatientsFilesQuery());
        return View(PatientsFiles);
    }

    [HttpGet]
    public async Task<IActionResult> CreateAsync()
    {
        var command = new CreateCustomerDataCommand();
        await FillCustomerDataDDLAsync(command);
        return View(command);
    }

    [HttpPost]
    public async Task<IActionResult> CreateAsync(CreateCustomerDataCommand command/*, IFormCollection form*/)
    {
        if (ModelState.IsValid)
        {
            #region is National Address Not Null
            var isNationalAddressNotNull = command.NationalAddressVM.GetType()
                                                  .GetProperties() //get all properties on object
                                                  .Select(pi => pi.GetValue(command.NationalAddressVM)) //get value for the property
                                                  .Any(value => value != null); // Check if one of the values is not null, if so it returns true.

            if (!isNationalAddressNotNull)
                command.NationalAddressVM = null;
            #endregion

            #region is Medical Insurance Not Null
            var isMedicalInsuranceNotNull = command.MedicalInsuranceVM.GetType()
                 .GetProperties() //get all properties on object
                 .Select(pi => pi.GetValue(command.MedicalInsuranceVM)) //get value for the property
                 .Any(value => value != null); // Check if one of the values is not null, if so it returns true.
            
            if(!isMedicalInsuranceNotNull)
                command.MedicalInsuranceVM = null;
            #endregion

            string? MedicalImagePath = null;
            var CustomerImagePath = (command.CustomerDataVM.CustomerImage != null) ? command.CustomerDataVM.CustomerMRN 
                                  + command.CustomerDataVM.CustomerImage.FileName.Substring(command.CustomerDataVM.CustomerImage.FileName.LastIndexOf('.')) : null;
            
            if(command.CustomerDataVM.Id == 0 || (command.CustomerDataVM.Id > 0 && CustomerImagePath != null))
                command.CustomerDataVM.ImageUrl = CustomerImagePath;

            if (command.MedicalInsuranceVM != null)
            {
                MedicalImagePath = (command.MedicalInsuranceVM.CardImage != null) ? command.CustomerDataVM.CustomerMRN
                                  + command.MedicalInsuranceVM.CardImage.FileName.Substring(command.MedicalInsuranceVM.CardImage.FileName.LastIndexOf('.')) : null;
                
                if (command.MedicalInsuranceVM.Id == 0 || (command.MedicalInsuranceVM.Id > 0 && MedicalImagePath != null))
                    command.MedicalInsuranceVM.CardImageUrl = MedicalImagePath;

            }
            
            var isSuccess = await Mediator.Send(command);
            if (isSuccess)
            {
                if (CustomerImagePath != null)
                    _fileHandler.UploadFile("CustomerData", command.CustomerDataVM.CustomerImage, command.CustomerDataVM.CustomerMRN);

                if (MedicalImagePath != null)
                    _fileHandler.UploadFile("MedicalInsurance", command.MedicalInsuranceVM.CardImage, command.CustomerDataVM.CustomerMRN);


                return RedirectToAction("Index");
            }
        }
        await FillCustomerDataDDLAsync(command);
        return View(command);

    }

    [HttpGet]
    public async Task<IActionResult> EditAsync(int id)
    {
        if (id > 0)
        {
            var command = await Mediator.Send(new GetCustomerDataByIdQuery
            {
                Id = id,
            });

            if (command != null)
            {
                await FillCustomerDataDDLAsync(command);
                return RedirectToAction("Create", command);
            }
        }

        return RedirectToAction("Create",new CreateCustomerDataCommand());
    }

    public async Task<JsonResult> GetAllPatientsFiles(string customerMRN, string iDNumber, string clientName)
    {
        var PatientsFiles = await Mediator.Send(new GetAllPatientsFilesQuery
        {
            ClientName = clientName,
            CustomerMRN = customerMRN,
            IDNumber = iDNumber,
        });
        return Json(PatientsFiles);
    }

    public async Task<IActionResult> GetAllPatientsFilesByFilter(GetAllPatientsFilesQuery query)
    {
        var model = await Mediator.Send(query);
        return PartialView("_PatientsFilesList", model);
    }




    private async Task FillCustomerDataDDLAsync(CreateCustomerDataCommand command)
    {
        command.CustomerDataVM.Nationalities.Add(new SelectListItem { Text = Global.SelectOne, Value = "" });
        var Nationalities = await Mediator.Send(new GetAllNationalityQuery());
        command.CustomerDataVM.Nationalities.AddRange(Nationalities.Select(a => new SelectListItem { Text = a.NationalityNameAr, Value = a.Id.ToString() }));

        command.CustomerDataVM.Religiones.Add(new SelectListItem { Text = Global.SelectOne, Value = "" });
        var Religiones = await Mediator.Send(new GetAllDefReligionQuery());
        command.CustomerDataVM.Religiones.AddRange(Religiones.Select(a => new SelectListItem { Text = a.ReligionNameAr, Value = a.Id.ToString() }));

        command.CustomerDataVM.SocialStatuses.Add(new SelectListItem { Text = Global.SelectOne, Value = "" });
        var SocialStatus = await Mediator.Send(new GetAllSocialStatusQuery());
        command.CustomerDataVM.SocialStatuses.AddRange(SocialStatus.Select(a => new SelectListItem { Text = a.TypeNameAr, Value = a.Id.ToString() }));

        command.CustomerDataVM.IDTypes.Add(new SelectListItem { Text = Global.SelectOne, Value = "" });
        command.CustomerDataVM.IDTypes.Add(new SelectListItem { Text = nameof(IDType.Iqama), Value = ((int)IDType.Iqama).ToString() });
        command.CustomerDataVM.IDTypes.Add(new SelectListItem { Text = nameof(IDType.Hawia), Value = ((int)IDType.Hawia).ToString() });
        command.CustomerDataVM.IDTypes.Add(new SelectListItem { Text = nameof(IDType.Passport), Value = ((int)IDType.Passport).ToString() });


        //command.NationalAddressVM.Cities.Add(new SelectListItem { Text = Global.SelectOne, Value = "0" });
        //var Cities = await Mediator.Send(new GetAllCitiesQuery());
        //command.NationalAddressVM.Cities.AddRange(Cities.Select(a => new SelectListItem { Text = a.CityNameAr, Value = a.Id.ToString() }));

    }
}

src/WebUI/Controllers/PatientFileController.cs
using MediatR;
using Medical_Optics.Application.Common.Enums;
using Medical_Optics.Application.Common.Resources;
using Medical_Optics.Application.Optic.Complaint.Queries.GetById;
using Medical_Optics.Application.Optic.Diagnose.Commands.Create;
using Medical_Optics.Application.Optic.PatientFile.Commands.Create;
using Medical_Optics.Application.Optic.PatientFile.Queries.GetById;
using Medical_Optics.Application.Optic.PatientFile.Queries.GetNextVisit;
using Medical_Optics.Application.Optic.PatientFile.Queries.GetPatientComplaints;
using Medical_Optics.Application.Optic.PatientFile.Queries.GetPatientDiagnoseItems;
using Medical_Optics.Application.Optic.PatientFile.Queries.GetPatientDiagnosis;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Medical_Optics.WebUI.Controllers;
public class PatientFileController : BaseController
{
    public IActionResult Index()
    {
        return View();
    }

    [HttpGet]
    public async Task<IActionResult> CreateAsync(int? id)
    {
        var command = new CreatePatientMedicalFileCommand();
        if (id != null)
        {
            command.PatientDataVM = await Mediator.Send(new GetPatientFileByIdQuery
            {
                Id = id.Value,
            });
            
            command.ListPatientComplaints = await Mediator.Send(new GetPatientComplaintsQuery
            {
                ClientId = id.Value,
            });

            if(command.ListPatientComplaints != null)
                command.PatientComplaintVM.PatientMedicalFileId = command.ListPatientComplaints[0].PatientMedicalFileId;

            command.PatientComplaintVM.VisitNo = await Mediator.Send(new GetNextVisitByPatientIdQuery
            {
                ClientId = id.Value,
            });

            command.PatientDataVM.VisitNo = command.PatientComplaintVM.VisitNo;
            command.ClientId = id.Value;
            FillDDL(command);
            return View(command);
        }
        return View(command);
        
    }

    [HttpPost]
    public async Task<IActionResult> CreateAsync(CreatePatientMedicalFileCommand command)
    {
        if (ModelState.IsValid)
        {
            command.PatientDiagnoseVM = null;
            var isSuccess = await Mediator.Send(command);
            if (isSuccess)
            {
                FillDDL(command);
                command.ListPatientComplaints = await Mediator.Send(new GetPatientComplaintsQuery
                {
                    ClientId = command.ClientId,
                });
                return PartialView("_Complaint", command);
            }
        }
        return PartialView("_Complaint", command);


    }

    [HttpPost]
    public async Task<IActionResult> GetEducationtypesByName(GetPatientFileByIdQuery getPatientFileByIdQuery)
    {
        var model = await Mediator.Send(getPatientFileByIdQuery);
        return PartialView("_CustomerData", model);
    }

    [HttpPost]
    public async Task<IActionResult> SaveDiagnosisAsync([FromBody] PatientDiagnoseVM patientDiagnoseVM )
    {
        if (patientDiagnoseVM != null)
        {
            var command = new CreatePatientMedicalFileCommand
            {
                PatientComplaintVM = null,
                PatientDiagnoseVM = patientDiagnoseVM,
                ClientId = patientDiagnoseVM.ClientId,
                Id = patientDiagnoseVM.PatientMedicalFileId,
            };
            var isSuccess = await Mediator.Send(command);

            if (isSuccess)
            {
                //command.ListPatientDiagnoseItems = await Mediator.Send(new GetPatientDiagnoseItemsQuery
                //{
                //    ClientId = command.ClientId,
                //});
                //FillDDL(command);
                //return PartialView("_Diagnosis", command);
                return Json(true);

            }
            //return Json(true);
        }
        return Json(false);
    }

    private void FillDDL(CreatePatientMedicalFileCommand command)
    {
        //command.Sides.Add(new SelectListItem { Text = Global.SelectOne, Value = "" });
        command.Sides.Add(new SelectListItem { Text = nameof(Side.None), Value = ((int)Side.None).ToString() });
        command.Sides.Add(new SelectListItem { Text = nameof(Side.Right), Value = ((int)Side.Right).ToString() });
        command.Sides.Add(new SelectListItem { Text = nameof(Side.Left), Value = ((int)Side.Left).ToString() });
        command.Sides.Add(new SelectListItem { Text = nameof(Side.Bilateral), Value = ((int)Side.Bilateral).ToString() });

        //command.DiagnoseTypes.Add(new SelectListItem { Text = Global.SelectOne, Value = "" });
        command.DiagnoseTypes.Add(new SelectListItem { Text = nameof(DiagnoseType.Principal), Value = ((int)DiagnoseType.Principal).ToString() });
        command.DiagnoseTypes.Add(new SelectListItem { Text = nameof(DiagnoseType.Secondary), Value = ((int)DiagnoseType.Secondary).ToString() });

    }
}

src/WebUI/Views/CustomerData/Create.cshtml
@model CreateCustomerDataCommand
@{
    ViewData["Title"] = @Global.Add + " " + @Optic.CustomerData;
    Layout = "_OpticLayout";
}
<div class="card margin-card container-fluid yourdiv">
    <div class="card-header position-relative padding-card row">
        <div class="col-md-4">
            <span class="icon-page"></span> <h3 class="page-name">@Global.Add  @Optic.CustomerData</h3>
        </div>
        <div class="col-md-8">

            <div class="menu text-right">
                <partial name="_HeaderMenu" />

            </div>
        </div>
    </div>
    <div class="card-body max-height">
        <div class="padding-screen"></div>
        <div class="row">
            <div class="col-xl-2 col-lg-12 left-menu">

                <div class="card">
                    <div class="card-header back-green">
                        @Optic.OpticMedicalFile/@Global.Add /@Optic.CustomerData
                    </div>
                    <div class="card-body back-black">

                        <div id="acdnmenu">
                            <partial name="_LeftMenu" />
                        </div>

                    </div>
                </div>

            </div>

            <div class="col-xl-10 col-lg-12">

                <!--Page Content-->
                <form asp-controller="CustomerData" asp-action="Create" method="post" enctype="multipart/form-data">

                    <div class="parent-title">

                        <h3 class="name-title" id="Company-Name"><strong> بيانات العميل الاساسية</strong></h3>

                        <div class="display-information" style="display: block;">
                            <partial name="_CustomerData" model="Model" />
                        </div>

                    </div>

                    <!--   ...............Address.............  -->
                    <div class="parent-title">

                        <h3 class="name-title" id="Company-Name"><strong>العنوان الوطنى</strong></h3>

                        <div class="display-information">
                            <partial name="_NationalAddress" model="Model" />

                        </div>

                    </div>

                    <!--   ...............Medical Data..............  -->
                    <div class="parent-title">

                        <h3 class="name-title" id="Company-Name"><strong> التأمين الطبى</strong></h3>

                        <div class="display-information">
                            <partial name="_MedicalInsurance" model="Model" />
                        </div>

                    </div>

                    <div class="text-center">
                        <button type="submit" class="btn btn-warning btn-sm" style="min-width:150px;">حفظ</button>
                    </div>

                </form>
                <!--Page Content-->
            </div>

        </div>
    </div>
</div>
@section Scripts{
    <script src="~/js/pages/CustomerData/AddCustomerData.js"></script>
}

src/WebUI/Views/CustomerData/Index.cshtml
@model List<CustomerDataVM>
@{
    ViewData["Title"] = @Optic.PatientFile;
    Layout = "_OpticLayout";
}
<div class="card margin-card container-fluid yourdiv">
    <div class="card-header position-relative padding-card row">
        <div class="col-md-4">
            <span class="icon-page"></span> <h3 class="page-name">  @Optic.PatientFile</h3>
        </div>
        <div class="col-md-8">

            <div class="menu text-right">
                <partial name="_HeaderMenu" />

            </div>
        </div>
    </div>
    <div class="card-body max-height">
        <div class="padding-screen"></div>
        <div class="row">
            <div class="col-xl-2 col-lg-12 left-menu">

                <div class="card">
                    <div class="card-header back-green">
                        @Optic.OpticMedicalFile/@Optic.PatientFile
                    </div>
                    <div class="card-body back-black">

                        <div id="acdnmenu">
                            <partial name="_LeftMenu" />
                        </div>

                    </div>
                </div>

            </div>
                <div class="col-xl-10 col-lg-12">
                    <div class="filter-client">
                         <partial name="_SearchInCustomerData" model="new GetAllPatientsFilesQuery()" />

                    </div>
                    <div id="myWizard">
                    
                        <div class="row">
                        <div class="col-6">
                            <button class="btn-filter"><i class="fas fa-filter"></i></button>
                        </div>
                        <div class="col-6 text-right">
                            <ul id="myTab" class="nav-lists nav nav-tabs" style="display: inline-block;">
                                <li class="nav-item"><a class="nav-link active" id="ListView-tab" data-toggle="tab" href="#block-item"><i class="fas fa-th-large"></i> </a></li>
                                <li class="nav-item"><a class="nav-link" id="KendoGrid-tab" data-toggle="tab" onclick="RefreshGrid()" href="#list-item"> <i class="fas fa-list"></i></a></li>
                            </ul>
                            <div class="clear"></div>
                        </div>
                    </div>
                    
                        <div class="tab-content patient-data" id="myTabContent">
                        <div id="block-item" class="tab-pane fade active show">
                            <partial name="_PatientsFilesList" model="Model" />

                        </div>



                        <!-- ...........tab2......... -->

                        <div id="list-item" class="tab-pane fade ">
@*                            <div class="over-fixed">
                                
                            </div>*@
                            <div id="PatientsFilesGrid" @*class="over-fixed"*@>
                            </div>

                        </div>

                    </div>
                    
                    </div>

            </div>   



        </div>
    </div>
</div>
@section Scripts{
    <script asp-append-version="true" src="~/js/pages/CustomerData/ListPatientsFiles.js"></script>
}

src/WebUI/Views/CustomerData/_CustomerData.cshtml
@model CreateCustomerDataCommand 

<input type="hidden" asp-for="CustomerDataVM.Id" />
<input type="hidden" asp-for="CustomerDataVM.CreatedUserId" />
<input type="hidden" asp-for="CustomerDataVM.LastModifiedUserId" />
<input type="hidden" asp-for="CustomerDataVM.DeletedUserId" />
<input type="hidden" asp-for="CustomerDataVM.CreationDate" />
<input type="hidden" asp-for="CustomerDataVM.LastModifiedDate" />
<div class="row">
    <div class="col-lg-9 ">

        <div class="row">

            <label class="col-xl-2 col-lg-4 form-group"> @Global.PaymentType </label>

            <div class="col-xl-2 col-lg-3 col-6 form-group">

                <div class="custom-control custom-radio">
                    <input type="radio" class="custom-control-input" asp-for="CustomerDataVM.PayType" id="Cash" value="@((int)PayType.Cash)" checked>
                    <label class="custom-control-label" for="Cash">@Global.Cash</label>

                </div>
            </div>

            <div class="col-xl-2 col-lg-3 col-6 form-group">

                <div class="custom-control custom-radio mb-3">
                    <input type="radio" class="custom-control-input" asp-for="CustomerDataVM.PayType" id="Credit" value="@((int)PayType.Credit)">
                    <label class="custom-control-label" for="Credit">@Global.Credit </label>

                </div>
            </div>

        </div>

        <div class="row">

            <label class="col-lg-2 form-group ">@Optic.CustomerMRN</label>

            <div class="col-lg-4 form-group ">
                <input type="text" asp-for="CustomerDataVM.CustomerMRN" class="form-control input-sys">
                <span asp-validation-for="CustomerDataVM.CustomerMRN" class="text-danger"></span>
            </div>

            <label class="col-lg-2 form-group ">@Optic.CustomerFileNo</label>

            <div class="col-lg-4 form-group ">
                <input type="text" asp-for="CustomerDataVM.CustomerFileNo" class="form-control input-sys">
                <span asp-validation-for="CustomerDataVM.CustomerFileNo" class="text-danger"></span>
            </div>

        </div>


        <div class="row">

            <label class="col-lg-2 form-group ">@Optic.CustomerNameAr</label>

            <div class="col-lg-4 form-group ">
                <input type="text" asp-for="CustomerDataVM.CustomerNameAr" class="form-control input-sys">
                <span asp-validation-for="CustomerDataVM.CustomerNameAr" class="text-danger"></span>

            </div>

            <label class="col-lg-2 form-group ">@Optic.CustomerNameEn</label>

            <div class="col-lg-4 form-group ">
                <input type="text" asp-for="CustomerDataVM.CustomerNameEn" class="form-control input-sys">
                <span asp-validation-for="CustomerDataVM.CustomerNameEn" class="text-danger"></span>

            </div>
        </div>

        <div class="row">

            <label class="col-lg-2 form-group ">@Optic.FatherName</label>

            <div class="col-lg-4 form-group ">
                <input type="text" asp-for="CustomerDataVM.FatherName" class="form-control input-sys">
                <span asp-validation-for="CustomerDataVM.FatherName" class="text-danger"></span>
            </div>

            <label class="col-lg-2 form-group ">@Optic.FamilyName</label>

            <div class="col-lg-4 form-group ">
                <input type="text" asp-for="CustomerDataVM.FamilyName" class="form-control input-sys">
                <span asp-validation-for="CustomerDataVM.FamilyName" class="text-danger"></span>
            </div>

        </div>

        <div class="row">

            <label class="col-lg-2 form-group ">@Global.BirthDate</label>

            <div class="col-lg-4 form-group ">
                <input type="date" asp-for="CustomerDataVM.BirthDate" class="form-control input-sys">
                <span asp-validation-for="CustomerDataVM.BirthDate" class="text-danger"></span>
            </div>

            <label class="col-lg-2 form-group ">@Optic.Age</label>

            <div class="col-lg-4 form-group ">
                <input type="number" asp-for="CustomerDataVM.Age" class="form-control input-sys" readonly>

            </div>

        </div>

        <div class="row">

            <label class="col-lg-2 form-group ">@Optic.IDType</label>

            <div class="col-lg-4 form-group ">
                <select asp-for="CustomerDataVM.IDType" asp-items="Model.CustomerDataVM.IDTypes" class="form-control input-sys">
                </select>
                <span asp-validation-for="CustomerDataVM.IDType" class="text-danger"></span>
            </div>

            <label class="col-lg-2 form-group ">  @Optic.IDNumber</label>

            <div class="col-lg-4 form-group ">
                <input type="text" asp-for="CustomerDataVM.IDNumber" class="form-control input-sys">
                <span asp-validation-for="CustomerDataVM.IDNumber" class="text-danger"></span>
            </div>

        </div>

        <div class="row">

            <label class="col-lg-2 form-group ">  @Global.Phone1</label>

            <div class="col-lg-4 form-group ">
                <input type="text" asp-for="CustomerDataVM.Phone" class="form-control input-sys">
                <span asp-validation-for="CustomerDataVM.Phone" class="text-danger"></span>

            </div>

            <label class="col-lg-2 form-group ">  @Global.Mobile</label>

            <div class="col-lg-4 form-group ">
                <input type="text" asp-for="CustomerDataVM.Mobile" class="form-control input-sys">
                <span asp-validation-for="CustomerDataVM.Mobile" class="text-danger"></span>

            </div>

        </div>

        <div class="row">

            <label class="col-xl-2 col-lg-4 form-group"> @Global.Type </label>

            <div class="col-xl-2 col-lg-3 col-6 form-group">

                <div class="custom-control custom-radio">
                    <input type="radio" class="custom-control-input" asp-for="CustomerDataVM.Gender" id="Male" value="@((int)Gender.Male)" checked>
                    <label class="custom-control-label" for="Male">@Optic.Male</label>

                </div>
            </div>

            <div class="col-xl-2 col-lg-3 col-6 form-group">

                <div class="custom-control custom-radio mb-3">
                    <input type="radio" class="custom-control-input" asp-for="CustomerDataVM.Gender" id="Female" value="@((int)Gender.Female)">
                    <label class="custom-control-label" for="Female">@Optic.Female </label>

                </div>
            </div>

        </div>

        <div class="row">

            <label class="col-lg-2 form-group ">@Optic.Nationality</label>

            <div class="col-lg-4 form-group ">
                <select asp-for="CustomerDataVM.NationalityId" asp-items="Model.CustomerDataVM.Nationalities" class="form-control input-sys">
                </select>

            </div>

            <label class="col-lg-2 form-group ">@Optic.Religion</label>

            <div class="col-lg-4 form-group ">
                <select asp-for="CustomerDataVM.ReligionId" asp-items="Model.CustomerDataVM.Religiones" class="form-control input-sys">
                </select>
            </div>


        </div>
        <div class="row">

            <label class="col-lg-2 form-group ">@Optic.SocialStatus</label>

            <div class="col-lg-4 form-group ">
                <select asp-for="CustomerDataVM.SocialStatusId" asp-items="Model.CustomerDataVM.SocialStatuses" class="form-control input-sys">
                    
                </select>

            </div>

            <label class="col-lg-2 form-group ">@Global.Email</label>

            <div class="col-lg-4 form-group ">
                <input type="text" asp-for="CustomerDataVM.Email" class="form-control input-sys">
                <span asp-validation-for="CustomerDataVM.Email" class="text-danger"></span>
            </div>
        </div>

        <div class="row">

            <label asp-for="CustomerDataVM.Description" class="col-xl-2 col-lg-3 form-group  ">
                @Global.Description
            </label>

            <div class="col-xl-8 col-lg-7 form-group ">
                <textarea asp-for="CustomerDataVM.Description" class="form-control input-sys"></textarea>

            </div>
        </div>

        <div class="row">

            <label class="col-xl-2 col-lg-4 form-group ">
                @Global.Status
            </label>

            <div class="col-xl-2 col-lg-3 col-6 form-group">

                <div class="custom-control custom-radio">
                    <input type="radio" asp-for="CustomerDataVM.IsActive" value="True" class="custom-control-input" id="rdActive" checked>
                    <label class="custom-control-label" for="rdActive">@Global.Active</label>

                </div>
            </div>

            <div class="col-xl-2 col-lg-3 col-6 form-group">

                <div class="custom-control custom-radio mb-3">
                    <input type="radio" class="custom-control-input" asp-for="CustomerDataVM.IsActive" value="False" id="rdInactive">
                    <label class="custom-control-label" for="rdInactive">@Global.Inactive</label>

                </div>
            </div>

        </div>


    </div>


    <div class="col-lg-3">
        <div class="image-upload">
            @if (Model.CustomerDataVM.Id > 0)
            {
                <input type="hidden" asp-for="CustomerDataVM.ImageUrl" value="@Model.CustomerDataVM.ImageUrl" />
                <a href="~/images/@Model.CustomerDataVM.ImageUrl" data-imagelightbox="Medical" data-ilb2-caption="كارت التامين">
                    <img src="~/images/@Model.CustomerDataVM.ImageUrl" id="customerImage">
                </a>
            }
            else
            {
                <a href="~/images/back-login.jpg" data-imagelightbox="Medical" data-ilb2-caption="كارت التامين">
                    <img src="~/images/back-login.jpg" id="customerImage">
                </a>
            }
            <label asp-for="CustomerDataVM.CustomerImage">@Optic.CustomerImage</label>
            <input type="file" asp-for="CustomerDataVM.CustomerImage" accept=".gif, .jpg, .png" onchange="setCustomerImage(this)" style="display:none;">
        </div>
    </div>


</div>

src/WebUI/Views/CustomerData/_PatientsFilesList.cshtml
@model List<CustomerDataVM>
@*href="M-Patient-File-inner.html"*@

<div class="paging-1">

    <ul class="row ul-clients content">
        @foreach (var patient in Model)
        {
            <li class="col-lg-4 col-md-6">
                <a asp-controller="PatientFile" asp-action="Create" asp-route-id="@patient.Id" class="hvr-hang">
                    <img src="~/images/@patient.ImageUrl" />
                    <div class="container-client">

                        <h5 class="name-client">@patient.CustomerMRN @patient.CustomerNameEn </h5>
                        <h6>@patient.Email</h6>
                        <h6>@patient.Mobile</h6>
                        <div class="row">
                            <div class="col-6">
                                <h5 class="visit-client">Visit</h5>
                            </div>
                            <div class="col-6">
                                <h5 class="date-client">@patient.BirthDate.Value.ToShortDateString()</h5>
                            </div>
                        </div>

                    </div>

                </a>
            </li>

        }

    </ul>

    <br>
    <div class="page_navigation"></div>

    <div class="clear"></div>

</div>