src/WebUI/Controllers/NationalityController.cs
using AutoMapper;
using Medical_Optics.Application.Def.City.Commands.Update;
using Medical_Optics.Application.Def.Nationality.Commands.Create;
using Medical_Optics.Application.Def.Nationality.Commands.Delete;
using Medical_Optics.Application.Def.Nationality.Commands.Update;
using Medical_Optics.Application.Def.Nationality.Queries.GetAll;
using Medical_Optics.Application.Def.Nationality.Queries.GetById;
using Medical_Optics.Domain.Entities.Optic;
using Microsoft.AspNetCore.Mvc;

namespace Medical_Optics.WebUI.Controllers;
public class NationalityController : BaseController
{
    private readonly IMapper _mapper;

    public NationalityController(IMapper mapper)
    {
        _mapper = mapper;
    }
    public IActionResult Index()
    {
        return View();
    }

    [HttpGet]
    public IActionResult Create()
    {
        return View(new CreateNationalityCommand());
    }

    [HttpPost]
    public async Task<IActionResult> CreateAsync(CreateNationalityCommand command)
    {
        if (ModelState.IsValid)
        {
            var isSuccess = await Mediator.Send(command);
            return isSuccess ? View("Index") : (IActionResult)View(command);
        }
        return View(command);
    }

    [HttpGet]
    public async Task<IActionResult> EditAsync(int id)
    {
        if (id > 0)
        {
            var nationality = await Mediator.Send(new GetlNationalityByIdQuery
            {
                Id = id,
            });
            if (nationality != null)
            {
                var result = _mapper.Map<UpdateNationalityCommand>(nationality);
                return View(result);
            }
        }

        return View(new UpdateNationalityCommand());
    }

    [HttpPost]
    public async Task<IActionResult> EditAsync(UpdateNationalityCommand command)
    {
        if (ModelState.IsValid)
        {
            var isSuccess = await Mediator.Send(command);
            return isSuccess ? View("Index") : (IActionResult)View(command);
        }
        return View(command);
    }

    [HttpPost]
    public async Task<JsonResult> DeleteAsync(int id)
    {
        if (id > 0)
        {
            var isSuccess = await Mediator.Send(
              new DeleteNationalityCommand
              {
                  Id = id
              });
            return Json(isSuccess);
        }
        return Json(new DeleteNationalityCommand());
    }

    public async Task<JsonResult> GetAll()
    {
        var Nationalities = await Mediator.Send(new GetAllNationalityQuery());
        return Json(Nationalities);
    }
}

src/WebUI/Views/Nationality/Create.cshtml
@model CreateNationalityCommand
@{
    ViewData["Title"] = @Global.Add + " " + @Optic.Nationality;
    Layout = "_OpticLayout";
}
<div class="card margin-card container-fluid yourdiv">
    <div class="card-header position-relative padding-card row">
        <div class="col-md-4">
            <span class="icon-page"></span> <h3 class="page-name">@Global.Add  @Optic.Nationality</h3>
        </div>
        <div class="col-md-8">

            <div class="menu text-right">
                <partial name="_HeaderMenu" />

            </div>
        </div>
    </div>
    <div class="card-body max-height">
        <div class="padding-screen"></div>
        <div class="row">
            <div class="col-xl-2 col-lg-12 left-menu">

                <div class="card">
                    <div class="card-header back-green">
                        @Optic.OpticMedicalFile/@Global.Add /@Optic.Nationality
                    </div>
                    <div class="card-body back-black">

                        <div id="acdnmenu">
                            <partial name="_LeftMenu" />
                        </div>

                    </div>
                </div>

            </div>

            <div class="col-xl-10 col-lg-12">

                <!--Page Content-->
                <form asp-controller="Nationality" asp-action="Create" method="post" class="row" enctype="multipart/form-data">
                    <div class="col-lg-12 ">
                        <div class="row">
                            <label asp-for="NationalityCode" class="col-xl-2 col-lg-3 form-group">@Global.Code</label>

                            <div class="col-xl-3 col-lg-3 form-group ">
                                <input type="text" asp-for="NationalityCode" class="form-control input-sys">
                                <span asp-validation-for="NationalityCode" class="text-danger"></span>
                            </div>

                        </div>

                        <div class="row">
                            <div class="col-xl-2 col-lg-3 ">
                                <label asp-for="NationalityNameAr" class="form-group"> @Global.NameAr</label>
                                <span class="text-danger" style="float:@Style.Float">*</span>
                            </div>
                            <div class="col-xl-3 col-lg-3 form-group ">
                                <input type="text" class="form-control input-sys" asp-for="NationalityNameAr">
                                <span asp-validation-for="NationalityNameAr" class="text-danger"></span>
                            </div>
                            <div class="col-xl-2 col-lg-3 ">
                                <label asp-for="NationalityNameEn" class="form-group">
                                    @Global.NameEn
                                </label>
                                <span class="text-danger" style="float:@Style.Float">*</span>
                            </div>

                            <div class="col-xl-3 col-lg-3 form-group ">
                                <input asp-for="NationalityNameEn" type="text" class="form-control input-sys">
                                <span asp-validation-for="NationalityNameEn" class="text-danger"></span>
                            </div>

                        </div>

                        <div class="row">

                            <label asp-for="Description" class="col-xl-2 col-lg-3 form-group  ">
                                @Global.Description
                            </label>

                            <div class="col-xl-8 col-lg-7 form-group ">
                                <textarea asp-for="Description" class="form-control input-sys" id="Description"></textarea>

                            </div>
                        </div>

                        <div class="row">

                            <label asp-for="IsActive" class="col-xl-2 col-lg-3 form-group ">@Global.Status</label>

                            <div class="col-xl-2 col-lg-3 col-6 form-group">
                                <div class="custom-control custom-radio">
                                    <input type="radio" asp-for="IsActive" value="True" class="custom-control-input" id="rdActive" checked>
                                    <label class="custom-control-label" for="rdActive">@Global.Active</label>

                                </div>
                            </div>

                            <div class="col-xl-2 col-lg-3 col-6 form-group">
                                <div class="custom-control custom-radio mb-3">
                                    <input type="radio" class="custom-control-input" asp-for="IsActive" value="False" id="rdInactive">
                                    <label class="custom-control-label" for="rdInactive">@Global.Inactive</label>
                                </div>
                            </div>
                        </div>

                    </div>
                    <br>
                    <div class="text-center">
                        <button type="submit" class="btn btn-success btn-sm"><i class="fas fa-save"></i> @Global.Save</button>
                        <a asp-action="Index" class="btn btn-dark btn-sm"><i class="fas fa-arrow-left"></i> @Global.Back</a>

                    </div>

                </form>
                <!--Page Content-->
            </div>

        </div>
    </div>
</div>

src/WebUI/Views/Nationality/Edit.cshtml
@model UpdateNationalityCommand
@{
    ViewData["Title"] = @Global.Edit + " " + @Optic.Nationality;
    Layout = "_OpticLayout";
}
<div class="card margin-card container-fluid yourdiv">
    <div class="card-header position-relative padding-card row">
        <div class="col-md-4">
            <span class="icon-page"></span> <h3 class="page-name">@Global.Edit  @Optic.Nationality</h3>
        </div>
        <div class="col-md-8">

            <div class="menu text-right">
                <partial name="_HeaderMenu" />

            </div>
        </div>
    </div>
    <div class="card-body max-height">
        <div class="padding-screen"></div>
        <div class="row">
            <div class="col-xl-2 col-lg-12 left-menu">

                <div class="card">
                    <div class="card-header back-green">
                        @Optic.OpticMedicalFile/@Global.Edit /@Optic.Nationality
                    </div>
                    <div class="card-body back-black">

                        <div id="acdnmenu">
                            <partial name="_LeftMenu" />
                        </div>

                    </div>
                </div>

            </div>

            <div class="col-xl-10 col-lg-12">

                <!--Page Content-->
                <form asp-controller="Nationality" asp-action="Edit" method="post" class="row" enctype="multipart/form-data">
                    <div class="col-lg-12 ">
                        <input type="hidden" asp-for="Id" />

                        <div class="row">
                            <label asp-for="NationalityCode" class="col-xl-2 col-lg-3 form-group">@Global.Code</label>

                            <div class="col-xl-3 col-lg-3 form-group ">
                                <input type="text" asp-for="NationalityCode" class="form-control input-sys">
                                <span asp-validation-for="NationalityCode" class="text-danger"></span>
                            </div>

                        </div>

                        <div class="row">
                            <div class="col-xl-2 col-lg-3 ">
                                <label asp-for="NationalityNameAr" class="form-group"> @Global.NameAr</label>
                                <span class="text-danger" style="float:@Style.Float">*</span>
                            </div>
                            <div class="col-xl-3 col-lg-3 form-group ">
                                <input type="text" class="form-control input-sys" asp-for="NationalityNameAr">
                                <span asp-validation-for="NationalityNameAr" class="text-danger"></span>
                            </div>
                            <div class="col-xl-2 col-lg-3 ">
                                <label asp-for="NationalityNameEn" class="form-group">
                                    @Global.NameEn
                                </label>
                                <span class="text-danger" style="float:@Style.Float">*</span>
                            </div>

                            <div class="col-xl-3 col-lg-3 form-group ">
                                <input asp-for="NationalityNameEn" type="text" class="form-control input-sys">
                                <span asp-validation-for="NationalityNameEn" class="text-danger"></span>
                            </div>

                        </div>

                        <div class="row">

                            <label asp-for="Description" class="col-xl-2 col-lg-3 form-group  ">
                                @Global.Description
                            </label>

                            <div class="col-xl-8 col-lg-7 form-group ">
                                <textarea asp-for="Description" class="form-control input-sys" id="Description"></textarea>

                            </div>
                        </div>

                        <div class="row">

                            <label asp-for="IsActive" class="col-xl-2 col-lg-3 form-group ">@Global.Status</label>

                            <div class="col-xl-2 col-lg-3 col-6 form-group">
                                <div class="custom-control custom-radio">
                                    <input type="radio" asp-for="IsActive" value="True" class="custom-control-input" id="rdActive" checked>
                                    <label class="custom-control-label" for="rdActive">@Global.Active</label>

                                </div>
                            </div>

                            <div class="col-xl-2 col-lg-3 col-6 form-group">
                                <div class="custom-control custom-radio mb-3">
                                    <input type="radio" class="custom-control-input" asp-for="IsActive" value="False" id="rdInactive">
                                    <label class="custom-control-label" for="rdInactive">@Global.Inactive</label>
                                </div>
                            </div>
                        </div>

                    </div>
                    <br>
                    <div class="text-center">
                        <button type="submit" class="btn btn-success btn-sm"><i class="fas fa-save"></i> @Global.Save</button>
                        <a asp-action="Index" class="btn btn-dark btn-sm"><i class="fas fa-arrow-left"></i> @Global.Back</a>

                    </div>

                </form>
                <!--Page Content-->
            </div>

        </div>
    </div>
</div>

src/WebUI/Views/Nationality/Index.cshtml
@model CreateNationalityCommand
@{
    ViewData["Title"] = @Optic.Nationality;
    Layout = "_OpticLayout";
}
<div class="card margin-card container-fluid yourdiv">
    <div class="card-header position-relative padding-card row">
        <div class="col-md-4">
            <span class="icon-page"></span> <h3 class="page-name">  @Optic.Nationality</h3>
        </div>
        <div class="col-md-8">

            <div class="menu text-right">
                <partial name="_HeaderMenu" />

            </div>
        </div>
    </div>
    <div class="card-body max-height">
        <div class="padding-screen"></div>
        <div class="row">
            <div class="col-xl-2 col-lg-12 left-menu">

                <div class="card">
                    <div class="card-header back-green">
                        @Optic.OpticMedicalFile/@Optic.Nationality
                    </div>
                    <div class="card-body back-black">

                        <div id="acdnmenu">
                            <partial name="_LeftMenu" />
                        </div>

                    </div>
                </div>

            </div>

            <div class="col-xl-10 col-lg-12">

                <!--Page Content-->
                <button type="button" class="btn btn-outline-success exportExcel" style="float:left;">@Global.Export<i class="fa fa-file-excel"></i></button>
                <a class="btn btn-success btn-sm btn-add" asp-action="Create"><i class="fas fa-plus"></i>@Global.AddNew</a>
                <br />
                <div id="NationalityGrid"></div>
                <!--Page Content-->
            </div>

        </div>
    </div>
</div>

@section Scripts{
    <script src="~/js/Pages/Nationality/ListNationality.js"></script>
}