src/WebUI/Controllers/ComplaintController.cs
using AutoMapper;
using Medical_Optics.Application.Common.Interfaces;
using Medical_Optics.Application.Favorite.Complaint.Queries.GetAll;
using Medical_Optics.Application.Optic.Complaint.Commands.Create;
using Medical_Optics.Application.Optic.Complaint.Commands.Delete;
using Medical_Optics.Application.Optic.Complaint.Commands.Update;
using Medical_Optics.Application.Optic.Complaint.Queries.GetAll;
using Medical_Optics.Application.Optic.Complaint.Queries.GetById;
using Microsoft.AspNetCore.Mvc;

namespace Medical_Optics.WebUI.Controllers;
public class ComplaintController : BaseController
{
    private readonly IMapper _mapper;
    private readonly IFileHandler _fileHandler;

    public ComplaintController(IMapper mapper, IFileHandler fileHandler)
    {
        _mapper = mapper;
        _fileHandler = fileHandler;
    }

    public IActionResult Index()
    {
        return View();
    }

    [HttpGet]
    public IActionResult Create()
    {
        return View(new CreateComplaintCommand());
    }

    [HttpPost]
    public async Task<IActionResult> CreateAsync(CreateComplaintCommand command)
    {
        if(ModelState.IsValid)
        {
        var ComplaintImagePath = (command.ComplaintImage != null) ? command.ComplaintCode + command.ComplaintImage.FileName.Substring(command.ComplaintImage.FileName.LastIndexOf('.')) : null;
        command.ComplaintImagePath = ComplaintImagePath;
        var isSuccess = await Mediator.Send(command);
        if(isSuccess)
        {
            if (ComplaintImagePath != null)
                _fileHandler.UploadFile("Complaints", command.ComplaintImage, command.ComplaintCode.ToString());
            
            return View("Index");
        }
        }
        return View(command);
    }
    [HttpGet]
    public async Task<IActionResult> EditAsync(int id)
    {
        if (id > 0)
        {
            var complaint = await Mediator.Send(new GetComplaintByIdQuery
            {
                Id = id,
                                                });
            if(complaint != null)
            {
                var result = _mapper.Map<UpdateComplaintCommand>(complaint);
                return View(result);
            }
        }

        return View(new UpdateComplaintCommand());
    }

    [HttpPost]
    public async Task<IActionResult> EditAsync(UpdateComplaintCommand command)
    {
        if (ModelState.IsValid)
        {
            var complaintImagePath = (command.ComplaintImage != null) ? command.ComplaintCode + command.ComplaintImage.FileName.Substring(command.ComplaintImage.FileName.LastIndexOf('.')) : null;
            if (complaintImagePath != null)
                command.ComplaintImagePath = complaintImagePath;

            var isSuccess = await Mediator.Send(command);
            if (isSuccess)
            {
                if (complaintImagePath != null)
                    _fileHandler.UploadFile("Complaints", command.ComplaintImage, command.ComplaintCode.ToString());

                return View("Index");
            }
        }
        return View(command);
    }

    [HttpPost]
    public async Task<JsonResult> DeleteAsync(int id)
    {
        var isSuccess = await Mediator.Send(
            new DeleteComplaintCommand {
                Id = id
            });
        return Json(isSuccess);
    }

    public async Task<JsonResult> GetAll()
    {
        var Complaints = await Mediator.Send(new GetAllComplaintsQuery());
        return Json(Complaints);
    }

    public async Task<JsonResult> GetAllOptional(string selectedIds)
    {
        List<int> optionalListIds = null;

        if (selectedIds != null)
            optionalListIds = selectedIds.Split(',').Select(Int32.Parse).ToList();

        var Complaints = await Mediator.Send(new GetAllComplaintsQuery
        {
            OptionalIds = optionalListIds
        });

        return Json(Complaints);
    }

    public async Task<JsonResult> GetAllSelected(string selectedIds)
    {
        List<int> selectedListIds = null;

        if (selectedIds != null)
            selectedListIds = selectedIds.Split(',').Select(Int32.Parse).ToList();

        var Complaints = await Mediator.Send(new GetAllSelectedComplaintsQuery
        {
            SelectedIds = selectedListIds
        });

        return Json(Complaints);
    }
}

src/WebUI/Controllers/SubComplaintController.cs
using AutoMapper;
using Medical_Optics.Application.Optic.SubCompalint.Commands.Create;
using Medical_Optics.Application.Optic.SubCompalint.Commands.Delete;
using Medical_Optics.Application.Optic.SubCompalint.Commands.Update;
using Medical_Optics.Application.Optic.SubCompalint.Queries.GetAll;
using Medical_Optics.Application.Optic.SubCompalint.Queries.GetById;
using Microsoft.AspNetCore.Mvc;

namespace Medical_Optics.WebUI.Controllers;
public class SubComplaintController : BaseController
{
    private readonly IMapper _mapper;

    public SubComplaintController(IMapper mapper)
    {
        _mapper = mapper;
    }
    public IActionResult Index()
    {
        return View();
    }

    [HttpGet]
    public IActionResult Create()
    {
        return View(new CreateSubComplaintCommand());
    }

    [HttpPost]
    public async Task<IActionResult> Create(CreateSubComplaintCommand command)
    {
        if (ModelState.IsValid)
        {
            var isSuccess = await Mediator.Send(command);
            return isSuccess ? View("Index") : (IActionResult)View(command);
        }
        return View(command);

    }

    [HttpGet]
    public async Task<IActionResult> EditAsync(int id)
    {
        if (id > 0)
        {
            var subCompalint = await Mediator.Send(new GetSubComplaintByIdQuery
            {
                Id = id,
            });
            if (subCompalint != null)
            {
                var result = _mapper.Map<UpdateSubComplaintCommand>(subCompalint);
                return View(result);
            }
        }

        return View(new UpdateSubComplaintCommand());
    }

    [HttpPost]
    public async Task<IActionResult> EditAsync(UpdateSubComplaintCommand command)
    {
        if (ModelState.IsValid)
        {
            var isSuccess = await Mediator.Send(command);
            return isSuccess ? View("Index") : (IActionResult)View(command);
        }
        return View(command);
    }

    [HttpPost]
    public async Task<JsonResult> DeleteAsync(int id)
    {
        if (id > 0)
        {
            var isSuccess = await Mediator.Send(
              new DeleteSubComplaintCommand
              {
                  Id = id
              });
            return Json(isSuccess);
        }
        return Json(new DeleteSubComplaintCommand());
    }

    public async Task<JsonResult> GetAll()
    {
        var SubCompalints = await Mediator.Send(new GetAllSubCompalintQuery());
        return Json(SubCompalints);
    }

    public async Task<JsonResult> GetAllSubCompalintByComplaintId(int complaintId)
    {
        var SubCompalints = await Mediator.Send(new GetAllSubCompalintQuery
        {
            CompalintId = complaintId
        });
        return Json(SubCompalints);
    }

}

src/WebUI/Views/SubComplaint/Create.cshtml
@model CreateSubComplaintCommand
@{
    ViewData["Title"] = @Global.Add + " " + @Optic.SubComplaint;
    Layout = "_OpticLayout";
}
<div class="card margin-card container-fluid yourdiv">
    <div class="card-header position-relative padding-card row">
        <div class="col-md-4">
            <span class="icon-page"></span> <h3 class="page-name">@Global.Add  @Optic.SubComplaint</h3>
        </div>
        <div class="col-md-8">

            <div class="menu text-right">
                <partial name="_HeaderMenu" />

            </div>
        </div>
    </div>
    <div class="card-body max-height">
        <div class="padding-screen"></div>
        <div class="row">
            <div class="col-xl-2 col-lg-12 left-menu">

                <div class="card">
                    <div class="card-header back-green">
                        @Optic.OpticMedicalFile/@Global.Add /@Optic.SubComplaint
                    </div>
                    <div class="card-body back-black">

                        <div id="acdnmenu">
                            <partial name="_LeftMenu" />
                        </div>

                    </div>
                </div>

            </div>

            <div class="col-xl-10 col-lg-12">

                <!--Page Content-->
                <form asp-controller="SubComplaint" asp-action="Create" method="post" class="row" enctype="multipart/form-data">
                    <div class="col-lg-12 ">
                        <div class="row">
                            <label asp-for="SubComplaintCode" class="col-xl-2 col-lg-3 form-group">@Global.Code</label>

                            <div class="col-xl-3 col-lg-3 form-group ">
                                <input type="text" asp-for="SubComplaintCode" class="form-control input-sys">
                                <span asp-validation-for="SubComplaintCode" class="text-danger"></span>
                            </div>

                            <label asp-for="ComplaintId" class="col-xl-2 col-lg-3 form-group">@Global.Code</label>

                            <div class="col-xl-3 col-lg-3 form-group ">
                                <input type="text" asp-for="ComplaintId" class="form-control input-sys customDDL">
                                <span asp-validation-for="ComplaintId" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-xl-2 col-lg-3 ">
                                <label asp-for="SubComplaintNameAr" class="form-group"> @Global.NameAr</label>
                                <span class="text-danger" style="float:@Style.Float">*</span>
                            </div>
                            <div class="col-xl-3 col-lg-3 form-group ">
                                <input type="text" class="form-control input-sys" asp-for="SubComplaintNameAr">
                                <span asp-validation-for="SubComplaintNameAr" class="text-danger"></span>
                            </div>
                            <div class="col-xl-2 col-lg-3 ">
                                <label asp-for="SubComplaintNameEn" class="form-group">
                                    @Global.NameEn
                                </label>
                                <span class="text-danger" style="float:@Style.Float">*</span>
                            </div>

                            <div class="col-xl-3 col-lg-3 form-group ">
                                <input asp-for="SubComplaintNameEn" type="text" class="form-control input-sys">
                                <span asp-validation-for="SubComplaintNameEn" class="text-danger"></span>
                            </div>

                        </div>


                        <div class="row">

                            <label asp-for="Description" class="col-xl-2 col-lg-3 form-group  ">
                                @Global.Description
                            </label>

                            <div class="col-xl-8 col-lg-7 form-group ">
                                <textarea asp-for="Description" class="form-control input-sys" id="Description"></textarea>

                            </div>
                        </div>

                        <div class="row">

                            <label asp-for="IsActive" class="col-xl-2 col-lg-3 form-group ">@Global.Status</label>

                            <div class="col-xl-2 col-lg-3 col-6 form-group">
                                <div class="custom-control custom-radio">
                                    <input type="radio" asp-for="IsActive" value="True" class="custom-control-input" id="rdActive" checked>
                                    <label class="custom-control-label" for="rdActive">@Global.Active</label>

                                </div>
                            </div>

                            <div class="col-xl-2 col-lg-3 col-6 form-group">
                                <div class="custom-control custom-radio mb-3">
                                    <input type="radio" class="custom-control-input" asp-for="IsActive" value="False" id="rdInactive">
                                    <label class="custom-control-label" for="rdInactive">@Global.Inactive</label>
                                </div>
                            </div>
                        </div>

                    </div>

                    <br>
                    <div class="text-center">
                        <button type="submit" class="btn btn-success btn-sm"><i class="fas fa-save"></i> @Global.Save</button>
                        <a asp-action="Index" class="btn btn-dark btn-sm"><i class="fas fa-arrow-left"></i> @Global.Back</a>

                    </div>

                </form>
                <!--Page Content-->
            </div>

        </div>
    </div>
</div>
@section Scripts{
    <script src="~/js/pages/SubCompalint/AddSubComplaint.js"></script>
}

src/WebUI/Views/SubComplaint/Edit.cshtml
@model UpdateSubComplaintCommand
@{
    ViewData["Title"] = @Global.Add + " " + @Optic.SubComplaint;
    Layout = "_OpticLayout";
}
<div class="card margin-card container-fluid yourdiv">
    <div class="card-header position-relative padding-card row">
        <div class="col-md-4">
            <span class="icon-page"></span> <h3 class="page-name">@Global.Add  @Optic.SubComplaint</h3>
        </div>
        <div class="col-md-8">

            <div class="menu text-right">
                <partial name="_HeaderMenu" />

            </div>
        </div>
    </div>
    <div class="card-body max-height">
        <div class="padding-screen"></div>
        <div class="row">
            <div class="col-xl-2 col-lg-12 left-menu">

                <div class="card">
                    <div class="card-header back-green">
                        @Optic.OpticMedicalFile/@Global.Add /@Optic.SubComplaint
                    </div>
                    <div class="card-body back-black">

                        <div id="acdnmenu">
                            <partial name="_LeftMenu" />
                        </div>

                    </div>
                </div>

            </div>

            <div class="col-xl-10 col-lg-12">

                <!--Page Content-->
                <form asp-controller="Complaint" asp-action="Edit" method="post" class="row" enctype="multipart/form-data">
                    <div class="col-lg-12 ">
                        <input type="hidden" asp-for="Id" />
                        <div class="row">
                            <label asp-for="SubComplaintCode" class="col-xl-2 col-lg-3 form-group">@Global.Code</label>

                            <div class="col-xl-3 col-lg-3 form-group ">
                                <input type="text" asp-for="SubComplaintCode" class="form-control input-sys">
                                <span asp-validation-for="SubComplaintCode" class="text-danger"></span>
                            </div>

                        </div>

                        <div class="row">
                            <div class="col-xl-2 col-lg-3 ">
                                <label asp-for="SubComplaintNameAr" class="form-group"> @Global.NameAr</label>
                                <span class="text-danger" style="float:@Style.Float">*</span>
                            </div>
                            <div class="col-xl-3 col-lg-3 form-group ">
                                <input type="text" class="form-control input-sys" asp-for="SubComplaintNameAr">
                                <span asp-validation-for="SubComplaintNameAr" class="text-danger"></span>
                            </div>
                            <div class="col-xl-2 col-lg-3 ">
                                <label asp-for="SubComplaintNameEn" class="form-group">
                                    @Global.NameEn
                                </label>
                                <span class="text-danger" style="float:@Style.Float">*</span>
                            </div>

                            <div class="col-xl-3 col-lg-3 form-group ">
                                <input asp-for="SubComplaintNameEn" type="text" class="form-control input-sys">
                                <span asp-validation-for="SubComplaintNameEn" class="text-danger"></span>
                            </div>

                        </div>


                        <div class="row">

                            <label asp-for="Description" class="col-xl-2 col-lg-3 form-group  ">
                                @Global.Description
                            </label>

                            <div class="col-xl-8 col-lg-7 form-group ">
                                <textarea asp-for="Description" class="form-control input-sys" id="Description"></textarea>

                            </div>
                        </div>

                        <div class="row">

                            <label asp-for="IsActive" class="col-xl-2 col-lg-3 form-group ">@Global.Status</label>

                            <div class="col-xl-2 col-lg-3 col-6 form-group">
                                <div class="custom-control custom-radio">
                                    <input type="radio" asp-for="IsActive" value="True" class="custom-control-input" id="rdActive" checked>
                                    <label class="custom-control-label" for="rdActive">@Global.Active</label>

                                </div>
                            </div>

                            <div class="col-xl-2 col-lg-3 col-6 form-group">
                                <div class="custom-control custom-radio mb-3">
                                    <input type="radio" class="custom-control-input" asp-for="IsActive" value="False" id="rdInactive">
                                    <label class="custom-control-label" for="rdInactive">@Global.Inactive</label>
                                </div>
                            </div>
                        </div>

                    </div>

                    <br>
                    <div class="text-center">
                        <button type="submit" class="btn btn-success btn-sm"><i class="fas fa-save"></i> @Global.Save</button>
                        <a asp-action="Index" class="btn btn-dark btn-sm"><i class="fas fa-arrow-left"></i> @Global.Back</a>

                    </div>

                </form>
                <!--Page Content-->
            </div>

        </div>
    </div>
</div>

src/WebUI/Views/SubComplaint/Index.cshtml
@model CreateComplaintCommand
@{
    ViewData["Title"] = @Optic.Complaint;
    Layout = "_OpticLayout";
}
<div class="card margin-card container-fluid yourdiv">
    <div class="card-header position-relative padding-card row">
        <div class="col-md-4">
            <span class="icon-page"></span> <h3 class="page-name">  @Optic.Complaint</h3>
        </div>
        <div class="col-md-8">

            <div class="menu text-right">
                <partial name="_HeaderMenu" />

            </div>
        </div>
    </div>
    <div class="card-body max-height">
        <div class="padding-screen"></div>
        <div class="row">
            <div class="col-xl-2 col-lg-12 left-menu">

                <div class="card">
                    <div class="card-header back-green">
                        @Optic.OpticMedicalFile/@Optic.Complaint
                    </div>
                    <div class="card-body back-black">

                        <div id="acdnmenu">
                            <partial name="_LeftMenu" />
                        </div>

                    </div>
                </div>

            </div>

            <div class="col-xl-10 col-lg-12">

                <!--Page Content-->
                <button type="button" class="btn btn-outline-success exportExcel" style="float:left;">@Global.Export<i class="fa fa-file-excel"></i></button>
                <a class="btn btn-success btn-sm btn-add" asp-action="Create"><i class="fas fa-plus"></i>@Global.AddNew</a>
                <br />
                <div id="SubComplaintGrid">
                </div>
                <!--Page Content-->
            </div>

        </div>
    </div>
</div>
@section Scripts{
    <script src="~/js/pages/SubCompalint/ListSubComplaint.js"></script>
}